In [3]:
import numpy as np
classes=['A','B','C']
classes_dict = {c: np.identity(len(classes))[i,:] for i, c in
                    enumerate(classes)}
classes_dict

{'A': array([1., 0., 0.]), 'B': array([0., 1., 0.]), 'C': array([0., 0., 1.])}

In [11]:
X=np.array(list(map(classes_dict.get,'A')))
X

array([[1., 0., 0.]])

In [16]:
A=np.array([[1,2,3],
            [2,3,4],
            [3,4,5]])
print(A[:,1:-1])

[[2]
 [3]
 [4]]


In [2]:
import numpy as np
path='../data/cora/'
dataset='cora'
edges_unordered=np.genfromtxt('{}{}.cites'.format(path,dataset),dtype=np.int32)
print(edges_unordered)

[[     35    1033]
 [     35  103482]
 [     35  103515]
 ...
 [ 853118 1140289]
 [ 853155  853118]
 [ 954315 1155073]]


In [6]:
import scipy.sparse as sp
idx_features_labels=np.genfromtxt("{}{}.content".format(path,dataset),dtype=np.dtype(str))
    #读取feature
features=sp.csr_matrix(idx_features_labels[:,1:-1],dtype=np.float32)
#读取标签

#节点序号
idx=np.array(idx_features_labels[:,0],dtype=np.int32)
#节点map
idx_map={j:i for i ,j in enumerate(idx)}

In [8]:
features.shape

(2708, 1433)

In [11]:
len(idx_map)

2708

In [15]:
edges_unordered

array([[     35,    1033],
       [     35,  103482],
       [     35,  103515],
       ...,
       [ 853118, 1140289],
       [ 853155,  853118],
       [ 954315, 1155073]])

In [17]:
edges = np.array(list(map(idx_map.get, edges_unordered.flatten())),
                     dtype=np.int32).reshape(edges_unordered.shape)
edges

array([[ 163,  402],
       [ 163,  659],
       [ 163, 1696],
       ...,
       [1887, 2258],
       [1902, 1887],
       [ 837, 1686]])

In [19]:
def encode_onehot(labels):
    '''
    labels:输入一个类别标签
    output:return对应标签的独热编码数组
    '''
    classes=set(labels) #保证标签唯一
    classes_dict={c:np.identity(len(classes))[i,:] for i ,c in enumerate(classes)}
    labels_onehot=np.array(list(map(classes_dict.get,labels)),dtype=np.int32)
    return labels_onehot

In [21]:
labels = encode_onehot(idx_features_labels[:, -1])

In [22]:
adj=sp.coo_matrix((np.ones(edges.shape[0]),(edges[:,0],edges[:,1])),shape=(labels.shape[0],labels.shape[0]),dtype=np.float32)

In [24]:
adj.shape

(2708, 2708)

In [26]:
A=np.matrix([[1,2,3],[1,2,3],[1,2,3]])

In [31]:
B=sp.coo_matrix(A)
# print(np.array(B))
B.T.multiply(B.T>B)


<3x3 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in Compressed Sparse Row format>

In [14]:
edges_unordered.flatten()

array([     35,    1033,      35, ...,  853118,  954315, 1155073])

In [1]:
import torch


In [11]:
import numpy as np
A=np.matrix([[1,1,2],[1,1,2],[2,2,1]])

In [12]:
rowsum=np.array(A.sum(1))
rowsum

array([[4],
       [4],
       [5]])

In [15]:
r_inv=np.power(rowsum,-1).flatten()

ValueError: Integers to negative integer powers are not allowed.